iers80/RezeptApp/config/routes.rb
Rails.application.routes.draw do

  resources :ingredients
  resources :my_recipes

  resources :recipes do
    member do
      post 'toggle_favorite', to: "recipes#toggle_favorite"
    end
  end

  resources :favorites


  resources :categories do
    member do
      get :show_recipes
    end
  end

  devise_for :users
  # resource :user, only: [] do
  #   root 'home#index'
  #
  # end
  root 'home#index' do
    member do
      post 'toggle_favorite', to: "recipes#toggle_favorite"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

iers80/RezeptApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

iers80/RezeptApp/app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

iers80/RezeptApp/app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

iers80/RezeptApp/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

iers80/RezeptApp/app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :titel, :description,:directions, presence: true
  has_rich_text :content
  belongs_to :category
  belongs_to :user
  has_many :ingredients, :dependent => :delete_all
  accepts_nested_attributes_for :ingredients
  has_one_attached :recipeImage
  acts_as_favoritable

end

iers80/RezeptApp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  acts_as_favoritor
end

iers80/RezeptApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  protect_from_forgery with: :exception


end

iers80/RezeptApp/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index

    @categories = Category.all
  end
  def show_recipes
    @users=User.all
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end
end

iers80/RezeptApp/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: :index
  def index
    @users=User.all
    @recipes = current_user.favorited_by_type('Recipe')
  end
end

iers80/RezeptApp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :toggle_favorite

  def toggle_favorite
    @recipe = Recipe.find_by(id: params[:id])
    current_user.favorited?(@recipe)  ?current_user.unfavorite(@recipe) : current_user.favorite(@recipe)
  end
  def index
    @users=User.all
    @recipes = Recipe.all
  end
end

iers80/RezeptApp/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:text, :recipe_id)
    end
end

iers80/RezeptApp/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

iers80/RezeptApp/app/controllers/my_recipes_controller.rb
class MyRecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @users=User.all
    @user = current_user
    @recipes = @user.recipes
  end

end

iers80/RezeptApp/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: :toggle_favorite

  def toggle_favorite
    @recipe = Recipe.find_by(id: params[:id])
    current_user.favorited?(@recipe)  ?current_user.unfavorite(@recipe) : current_user.favorite(@recipe)
  end


  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
    @recipes.ingredients.build
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipes = Recipe.find(params[:id])

    @ingredients =  Ingredient.where(recipe_id: params[:id]).all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
  end

  # GET /recipes/1/edit
  def edit
  end



  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    if params[:add_ingredient]
      # add empty ingredient associated with @recipe
      @recipe.ingredients.build
    elsif params[:remove_ingredient]
      # nested model that have _destroy attribute = 1 automatically deleted by rails
    else
      # save goes like usual
      if @recipe.save
        flash[:notice] = "Successfully created recipe."
        redirect_to @recipe and return
      end
    end
    render :action => 'new'
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to my_recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:titel, :description, :user_id, :category_id,:directions,:recipeImage,:content,ingredients_attributes:[:text])
    end
end

iers80/RezeptApp/app/helpers/application_helper.rb
module ApplicationHelper
end

iers80/RezeptApp/app/helpers/categories_helper.rb
module CategoriesHelper
end

iers80/RezeptApp/app/helpers/home_helper.rb
module HomeHelper
end

iers80/RezeptApp/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

iers80/RezeptApp/app/helpers/my_recipes_helper.rb
module MyRecipesHelper
end

iers80/RezeptApp/app/helpers/recipes_helper.rb
module RecipesHelper
  def link_to_add_row(name, form, association, **args)
    new_object = form.object.send(association).klass.new
    id = new_object.object_id
    fields = form.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

iers80/RezeptApp/app/views/categories/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<%# if user_signed_in? %>
<!--  <div> Welcome <%#= current_user.email %> </div>-->
<%#= button_to "Sign out", destroy_user_session_path, method: :delete %>


<p class="h2 text-center mb-3">Kategorien</p>
<div class="container p-3">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @categories.each do |category| %>
      <%= link_to show_recipes_category_path(category) do %>
        <div class="col h-100">
            <div class="card h-100">
                <%=  image_tag(category.image_url,class:'catImage')%>
              <div class="card-body">
                <h5 class="card-title"><%= category.title %></h5>
              </div>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>





<%# else %>
<%#= button_to "Sign in", new_user_session_path %>
<%# end %>


iers80/RezeptApp/app/views/categories/show_recipes.html.erb


<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<%# if user_signed_in? %>
<!--  <div> Welcome <%#= current_user.email %> </div>-->


<div class="container" style="width: 900px">
  <div class="container">
    <div class="row justify-content-center p-2">
      <div class="col backgroundImage" style="background-image: url(<%= asset_path @category.image_url %>);">
        <div style="position: relative;">
          <p class="h1 text-center text-warning mb-3" ><%= @category.title %></p>
          <p class="text-center text-white  "><%= @category.description %></p>
        </div>
      </div>
    </div>
  </div>

  <%= render '/shared/recipeCard' %>

</div>


<%# else %>
<%#= button_to "Sign in", new_user_session_path %>
<%# end %>


iers80/RezeptApp/app/views/home/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<%# if user_signed_in? %>
<!--  <div> Welcome <%#= current_user.email %> </div>-->

<p class="h2 text-center mb-3">Was koche ich heute?</p>
<%= render '/shared/recipeCard' %>

<%# else %>
  <%#= button_to "Sign in", new_user_session_path %>
<%# end %>


iers80/RezeptApp/app/views/layouts/_modal.html.erb
<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="md-form mb-5">
          <i class="fas fa-envelope prefix grey-text"></i>
          <input type="email" id="defaultForm-email" class="form-control validate">
          <label data-error="wrong" data-success="right" for="defaultForm-email">Your email</label>
        </div>

        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          <input type="password" id="defaultForm-pass" class="form-control validate">
          <label data-error="wrong" data-success="right" for="defaultForm-pass">Your password</label>
        </div>

      </div>
      <div class="modal-footer d-flex justify-content-center">
        <button class="btn btn-default">Login</button>
      </div>
    </div>
  </div>
</div>

iers80/RezeptApp/app/views/layouts/_navigation.html.erb

<nav class="navbar navbar-expand-lg navbar-dark bg-primary ps-3 justify-content-between mb-5">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= image_tag("chef", :style => "width: 30px;" ) %>
      </li>
      <li class="nav-item active">
        <%= link_to "Home", root_path ,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Category", categories_path ,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Favorites", favorites_path ,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My Recipes", my_recipes_path ,class:"nav-link" %>
      </li>

    </ul>
  </div>

  <div class="row">
    <% if user_signed_in? %>
      <div class="col">
        <%= button_to "Sign out", destroy_user_session_path,class:"btn btn-primary", method: :delete %>
      </div>
    <% else %>
    <div class="col">
      <%= button_to "Sign in", new_user_session_path ,class:"btn btn-primary"%>
    </div>

    <% end %>
  </div>

</nav>

iers80/RezeptApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "RezeptAppa" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "RezeptApp" %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">




    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <header>
    <%= render 'layouts/navigation' %>
  </header>


  <%= yield %>
  </body>
</html>

iers80/RezeptApp/app/views/shared/_recipeCard.html.erb
<div class="container p-3">
  <div class="row row-cols-1 row-cols-md-4 g-4">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe, { class: "link" } do %>
        <div class="col h-100">
          <div class="card h-100">
            <% if recipe.recipeImage.attached? %>
              <img src="<%= (url_for(recipe.recipeImage)) %>">
            <% else %>
              <%= image_tag(recipe.image_url ) %>
            <% end %>

            <div class="card-body">
              <h5 class="card-title"><%= recipe.titel %></h5>
              <p>
                <%= @users.find_by(id:recipe.user_id).email %>
              </p>
              <div>
                <p>
                  <%= sanitize(recipe.description[0..50]) %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>



iers80/RezeptApp/app/views/shared/_recipeInhalt.html.erb
<div class="row justify-content-center p-2">
  <div class="col-8 recipes" <% if @recipe.recipeImage.attached? %>
       style="background-image: url(<%= rails_blob_url(@recipe.recipeImage)%>)"<% else %>
       style="background-image: url(<%= asset_path  @recipe.image_url %>)"
       <% end %> ;>
    <div style=" position: relative;">
      <% if user_signed_in?%>
        <% if @recipe.user_id != current_user.id%>

            <%= link_to toggle_favorite_recipe_path(@recipe),remote: true, method: :post   do %>
            <div class="like-icon mx-2 <%= 'red' if current_user.favorited?(@recipe) %>" data-id="<%= @recipe.id %>">
              <i class="fas fa-heart"></i>
            </div>
            <% end %>

        <% else %>
          <div class="dropdown">
            <i class="fa fa-ellipsis-v" style="color:white" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" aria-hidden="true"></i>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to 'Delete', @recipe, method: :delete, data: { confirm: 'Are you sure?' } ,class:"dropdown-item"%>
              <%= link_to 'Edit', edit_recipe_path(@recipe),class:"dropdown-item" %> |
            </div>
          </div>
        <% end %>
      <% else %>
        <%= button_to toggle_favorite_recipe_path(@recipe),class:"btn btn-outline-primary",method: :post do %>
          <i class="fa-regular fa-heart" style="color:red"></i>
        <% end %>
      <% end %>
      <p class="h1 text-center text-warning mb-3" ><%=  @recipe.titel %></p>
    </div>
  </div>
</div>